In [3]:
from netflows import Graph
import numpy as np
from scipy.io import loadmat

from netflows.funcs import WElinearsolve, WEaffinesolve, WEbprsolve
from netflows.funcs import SOlinearsolve, SOaffinesolve, SObprsolve

In [2]:
data = loadmat('/Users/yingqiuzheng/Desktop/Research/selfish_routing/data/G.mat')
data = data['G'][0][0]

# load rat data
rat = data[2][0][0]
rat_adj = rat[0]

In [4]:
import pickle
with open('modha_conn.pickle', 'rb') as f:
    modha = pickle.load(f)
    
modha_adj = modha['modha_adj']
modha_dist = modha['modha_dist']

FileNotFoundError: [Errno 2] No such file or directory: 'modha_conn.pickle'

In [42]:
G_modha = Graph(adj = modha_adj, dist=modha_dist, weights=modha_adj)

In [31]:
1/125

0.008

In [129]:
len(G_rat.findallpaths(0, 7))

1339

In [49]:
WElinearsolve(G_modha, 0, 200, tol=1e-7, maximum_iter=500000, cutoff=None)

Cutoff not specified: take shortest path distance + 1 as cutoff
The initial cost is 10.364415, and the initial flow is  [0.05882353 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353
 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353
 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353]
------solve the Wardrop Equilibrium------
Wardrop equilibrium found:
Iteration 57: The total cost is 9.103813, and the flow is  [0.12799548 0.07307488 0.12457578 0.         0.05154953 0.
 0.09662001 0.00801408 0.09728275 0.05708991 0.06375815 0.06322589
 0.0608266  0.07510298 0.         0.05272026 0.04816369]


(9.103813295224361,
 array([0.12799548, 0.07307488, 0.12457578, 0.        , 0.05154953,
        0.        , 0.09662001, 0.00801408, 0.09728275, 0.05708991,
        0.06375815, 0.06322589, 0.0608266 , 0.07510298, 0.        ,
        0.05272026, 0.04816369]))

In [9]:
#G.findallpaths(0, 3, cutoff=3)
for row in range(G_rat.adj.shape[0]):
    for col in range(G_rat.adj.shape[1]):
        if row == col:
            continue
        else:
            print('now computing the WE flow of node pair (%d, %d)' % (row, col))
            if G_rat.findallpaths(row, col):
                WElinearsolve(G_rat, row, col, tol=1e-8, maximum_iter=100000)

now computing the WE flow of node pair (0, 1)
The initial cost is 65.886858, and the initial flow is  [0.00210526 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526
 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526
 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526
 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526
 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526
 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526
 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526
 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526
 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526
 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526
 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526
 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526
 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526 0.00210526
 0.00210526 0.00210526 0.00

KeyboardInterrupt: 

In [50]:
with open('G_rat.pickle', 'rb') as f:
    G_rat = pickle.load(f)

In [52]:
G_rat = G_rat['G_rat']

In [67]:
from scipy.stats import pearsonr

In [84]:
pearsonr(G_rat.WEflowsLinear_edge.sum(axis=1), G_rat.wiring_cost.sum(axis = 1)+G_rat.wiring_cost.sum(axis = 0))

(0.9381636306362614, 1.964349058708812e-34)

In [77]:
G_rat.WEflowsLinear_edge.sum(axis = 0) / G_rat.WEflowsLinear.sum()

array([0.02573866, 0.06783585, 0.01846268, 0.03615553, 0.02405433,
       0.0680285 , 0.02694261, 0.0294664 , 0.01401626, 0.03961209,
       0.02451792, 0.0206711 , 0.06672141, 0.03700161, 0.02382771,
       0.03168493, 0.02402906, 0.02919127, 0.04580338, 0.024564  ,
       0.03082911, 0.02646459, 0.02322352, 0.04707388, 0.04617053,
       0.01706048, 0.02630128, 0.02028951, 0.01901878, 0.04989602,
       0.01519688, 0.05706675, 0.05112046, 0.0620288 , 0.02395315,
       0.0531992 , 0.02539853, 0.03799802, 0.04060134, 0.03512503,
       0.06413073, 0.03143809, 0.04588374, 0.03055811, 0.04143566,
       0.01987984, 0.03122918, 0.05487288, 0.13081338, 0.09419459,
       0.15902874, 0.09854227, 0.02186932, 0.02632256, 0.03401241,
       0.02786922, 0.03429642, 0.03464475, 0.02348811, 0.04948065,
       0.01681986, 0.02768316, 0.01943325, 0.01093672, 0.05922547,
       0.04828874, 0.02194075, 0.0591996 , 0.03984606, 0.0591725 ,
       0.02321292, 0.03920299, 0.01949057])

In [78]:
G_rat.wiring_cost.sum(axis = 0) / G_rat.wiring_cost.sum()

array([0.00457006, 0.01401677, 0.00516407, 0.01653653, 0.00901557,
       0.01896048, 0.00937006, 0.00634251, 0.0022994 , 0.01371976,
       0.00377485, 0.00676407, 0.02636647, 0.01605749, 0.01155449,
       0.00856527, 0.00856527, 0.0070994 , 0.01868263, 0.01104671,
       0.01290539, 0.01373892, 0.01804072, 0.01763832, 0.01674731,
       0.00461796, 0.01109461, 0.00637126, 0.00747305, 0.01745629,
       0.00318084, 0.01335569, 0.01845269, 0.01272335, 0.00634251,
       0.02742994, 0.00896766, 0.01183234, 0.01256048, 0.01988982,
       0.02877126, 0.01537725, 0.02655808, 0.01226347, 0.02468024,
       0.00799042, 0.00478084, 0.01701557, 0.03393533, 0.03107066,
       0.04326707, 0.01585629, 0.00297006, 0.00524072, 0.00916886,
       0.00782754, 0.00993533, 0.01367186, 0.00838323, 0.02281198,
       0.00445509, 0.00960958, 0.0048    , 0.00014371, 0.02495808,
       0.03302515, 0.00701317, 0.02003353, 0.01400719, 0.02897246,
       0.00617964, 0.01878802, 0.00714731])

In [86]:
G_rat.adj.sum(axis = 1)

array([20, 40,  9, 17, 14, 38, 17, 11,  6, 18, 17, 14, 31, 26, 12, 16, 22,
       24, 19, 14, 12, 14,  7, 22, 25, 12, 12, 15, 12, 24,  8, 41, 18, 43,
       18, 23, 22, 26, 30, 22, 30, 19, 21, 20, 16, 12, 27, 28, 46, 39, 44,
       41, 14, 21, 27, 21, 11, 21,  7, 13,  5, 11,  6,  4, 29, 21, 16, 26,
       26, 31, 19, 19, 10])

In [128]:
for k in range(min(G_rat.adj.sum(axis = 0).max(), G_rat.adj.sum(axis = 1).max())):
    rich_club_edges = np.outer(np.where(G_rat.adj.sum(axis = 1)>k, 1, 0), 
                               np.where(G_rat.adj.sum(axis = 0)>k, 1, 0) ) * G_rat.adj
    local_edges = np.outer(np.where(G_rat.adj.sum(axis = 1)<k, 1, 0), 
                               np.where(G_rat.adj.sum(axis = 0)<k, 1, 0) ) * G_rat.adj
    non_rich_club_edges = (1  - np.outer(np.where(G_rat.adj.sum(axis = 1)>k, 1, 0), 
                               np.where(G_rat.adj.sum(axis = 0)>k, 1, 0) )) * G_rat.adj
    #print('rich_club_ratio, rich_club_density_ratio, rich_club_flows_ratio')
    print(k)
    print(rich_club_edges.sum()/G_rat.adj.sum()/rich_club_edges.sum(), 
          (rich_club_edges * G_rat.wiring_cost).sum() / G_rat.wiring_cost.sum()/rich_club_edges.sum())
    print((rich_club_edges * G_rat.WEflowsLinear_edge).sum()/G_rat.WEflowsLinear.sum()/rich_club_edges.sum())
    print( ((rich_club_edges * G_rat.WEflowsLinear_edge).sum()/G_rat.WEflowsLinear.sum()/rich_club_edges.sum()) / 
    ((rich_club_edges * G_rat.wiring_cost).sum() / G_rat.wiring_cost.sum()/rich_club_edges.sum()) )
    #print((local_edges * G_rat.WEflowsLinear_edge).sum()/G_rat.WEflowsLinear.sum()/local_edges.sum())
    print(non_rich_club_edges.sum()/G_rat.adj.sum()/non_rich_club_edges.sum(), 
          (non_rich_club_edges * G_rat.wiring_cost).sum() / G_rat.wiring_cost.sum()/non_rich_club_edges.sum())
    print((non_rich_club_edges * G_rat.WEflowsLinear_edge).sum()/G_rat.WEflowsLinear.sum()/non_rich_club_edges.sum())
    print( ((non_rich_club_edges * G_rat.WEflowsLinear_edge).sum()/G_rat.WEflowsLinear.sum()/non_rich_club_edges.sum()) / 
    ((non_rich_club_edges * G_rat.wiring_cost).sum() / G_rat.wiring_cost.sum()/non_rich_club_edges.sum()) )
    

0
0.0006702412868632708 0.0006702412868632708
0.001933501623152319
2.88478442174326
nan nan
nan
nan
1
0.0006702412868632708 0.0006705944248324276
0.0019274632461665523
2.874260767450011
0.0006702412868632708 0.00014371257485029938
0.010936721708930156
76.10135522463901
2
0.0006702412868632708 0.0006705944248324276
0.0019274632461665523
2.874260767450011
0.0006702412868632708 0.00014371257485029938
0.010936721708930156
76.10135522463901
3
0.0006702412868632708 0.0006705944248324276
0.0019274632461665523
2.874260767450011
0.0006702412868632708 0.00014371257485029938
0.010936721708930156
76.10135522463901
4
0.0006702412868632708 0.0006708724538752109
0.0019127988907540975
2.8512109562779835
0.0006702412868632708 0.0005984339014279133
0.004288835562919203
7.16676570743349
5
0.0006702412868632708 0.0006715782865854404
0.001904025060107255
2.835149822648441
0.0006702412868632708 0.0005848476959125227
0.003816156888943576
6.5250438970941405
6
0.0006702412868632708 0.0006718670171717213
0.0018

/Users/yingqiuzheng/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:16: RuntimeWarning: invalid value encountered in double_scalars
/Users/yingqiuzheng/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:17: RuntimeWarning: invalid value encountered in double_scalars
/Users/yingqiuzheng/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:18: RuntimeWarning: invalid value encountered in double_scalars
/Users/yingqiuzheng/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:19: RuntimeWarning: invalid value encountered in double_scalars
/Users/yingqiuzheng/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:20: RuntimeWarning: invalid value encountered in double_scalars


In [100]:
G_rat.WEflowsLinear_edge.sum(axis = 0) / G_rat.WEflowsLinear.sum()

array([0.02573866, 0.06783585, 0.01846268, 0.03615553, 0.02405433,
       0.0680285 , 0.02694261, 0.0294664 , 0.01401626, 0.03961209,
       0.02451792, 0.0206711 , 0.06672141, 0.03700161, 0.02382771,
       0.03168493, 0.02402906, 0.02919127, 0.04580338, 0.024564  ,
       0.03082911, 0.02646459, 0.02322352, 0.04707388, 0.04617053,
       0.01706048, 0.02630128, 0.02028951, 0.01901878, 0.04989602,
       0.01519688, 0.05706675, 0.05112046, 0.0620288 , 0.02395315,
       0.0531992 , 0.02539853, 0.03799802, 0.04060134, 0.03512503,
       0.06413073, 0.03143809, 0.04588374, 0.03055811, 0.04143566,
       0.01987984, 0.03122918, 0.05487288, 0.13081338, 0.09419459,
       0.15902874, 0.09854227, 0.02186932, 0.02632256, 0.03401241,
       0.02786922, 0.03429642, 0.03464475, 0.02348811, 0.04948065,
       0.01681986, 0.02768316, 0.01943325, 0.01093672, 0.05922547,
       0.04828874, 0.02194075, 0.0591996 , 0.03984606, 0.0591725 ,
       0.02321292, 0.03920299, 0.01949057])

In [98]:
G_rat.WEflowsLinear_edge

array([[ 0.        , 13.89275015,  9.67614901, ...,  0.        ,
         0.        ,  0.        ],
       [22.2079116 ,  0.        , 22.46636125, ...,  0.        ,
         1.85796189,  0.        ],
       [11.17300288, 14.0123418 ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         2.25309715,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  5.78222008,
         0.        ,  8.18366506],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        19.31057586,  0.        ]])

In [127]:
for k in range(min(G_rat.adj.sum(axis = 0).max(), G_rat.adj.sum(axis = 1).max())):
    # degree threshold k
    in_hubs = np.where(G_rat.adj.sum(axis = 0)>k, 1, 0)
    out_hubs = np.where(G_rat.adj.sum(axis = 1)>k, 1, 0)
    in_flows = G_rat.WEflowsLinear_edge.sum(axis = 0)
    out_flows = G_rat.WEflowsLinear_edge.sum(axis = 1)
    print(k)
    print(G_rat.wiring_cost.sum(axis=1)[out_hubs==1].sum()/G_rat.wiring_cost.sum()/out_hubs.sum(), 
          out_flows[out_hubs==1].sum()/G_rat.WEflowsLinear.sum()/out_hubs.sum(), 
          out_flows[out_hubs==0].sum()/G_rat.WEflowsLinear.sum()/np.where(out_hubs==0, 1, 0).sum())
    print(G_rat.wiring_cost.sum(axis=0)[in_hubs==1].sum()/G_rat.wiring_cost.sum()/in_hubs.sum(), 
          in_flows[in_hubs==1].sum()/G_rat.WEflowsLinear.sum()/in_hubs.sum(), 
          in_flows[in_hubs==0].sum()/G_rat.WEflowsLinear.sum()/np.where(in_hubs==0, 1, 0).sum())

0
0.0136986301369863 0.03951759481840082 nan
0.0136986301369863 0.039517594818400816 nan
1
0.0136986301369863 0.03951759481840082 nan
0.013886892880904856 0.03991455138936569 0.010936721708930156
2
0.0136986301369863 0.03951759481840082 nan
0.013886892880904856 0.03991455138936569 0.010936721708930156
3
0.0136986301369863 0.03951759481840082 nan
0.013886892880904856 0.03991455138936569 0.010936721708930156
4
0.013876646706586825 0.03987225557242199 0.013982020528876862
0.01418716852010265 0.040614451142202676 0.01392428059635759
5
0.014037007674791263 0.040196937176359436 0.01540094111086979
0.0143466805519396 0.04098282167419272 0.014242431555990667
6
0.014341681853683935 0.040863498164919874 0.016300762090947118
0.014489749911940823 0.04133462079962908 0.014806041473696449
7
0.014618643310394133 0.04139179704341433 0.01858900330574998
0.014842487333026254 0.04211605629014368 0.018405095360490106
8
0.014765813826891669 0.04179157346439571 0.018077224727591875
0.014842487333026254 0.04

/Users/yingqiuzheng/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:10: RuntimeWarning: invalid value encountered in double_scalars
/Users/yingqiuzheng/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:13: RuntimeWarning: invalid value encountered in double_scalars


In [116]:
G_rat.WEflowsLinear_edge[G_rat.WEflowsLinear_edge!=0] / G_rat.WEflowsLinear.sum()

array([0.00264422, 0.00184167, 0.00157878, ..., 0.0014246 , 0.00523497,
       0.0036754 ])

In [120]:
pearsonr(G_rat.WEflowsLinear_edge[G_rat.adj!=0].flatten(), G_rat.wiring_cost[G_rat.adj!=0].flatten())

(0.6388581948012826, 6.496942514199329e-172)

In [6]:
with open('data/human033_adj.pickle', 'rb') as f:
    human033_adj = pickle.load(f)
    
with open('data/human033_dist.pickle', 'rb') as f:
    human033_dist = pickle.load(f)

In [7]:
G_human033 = Graph(adj=human033_adj, dist=human033_dist, weights=human033_adj)

In [8]:
with open('human033.pickle', 'rb') as f:
    results = pickle.load(f)

G_human033.WEflowsLinear_edge = results['total_flow_edge']
G_human033.WEcostsLinear_edge = results['total_time_edge']

G_human033.WEcostsLinear = results['total_time']

In [12]:
np.count_nonzero(G_human033.WEflowsLinear_edge) / 82 / 81

0.21348991267690454

In [13]:
G_human033.total_flow = results['total_flow']

In [14]:
G_human033.total_flow

6533

In [19]:
G_human033.degree = G_human033.adj.sum(axis = 0)
G_human033.strength = G_human033.adj_weights.sum(axis = 0)

In [16]:
G_human033.in_flow = G_human033.WEflowsLinear_edge.sum(axis = 0)
G_human033.out_flow = G_human033.WEflowsLinear_edge.sum(axis = 1)

In [31]:
from scipy.stats import pearsonr
pearsonr(G_human033.out_flow/G_human033.nodal_cost, G_human033.strength)

(-0.3603328764260892, 0.0008831871138107541)

In [46]:
# nodal cost and nodal flow
G_human033.nodal_time = G_human033.WEcostsLinear_edge.sum(axis = 0)

In [47]:
for k in range(G_human033.degree.max()):
    hubs = np.where(G_human033.degree>k, 1, 0)
    print(k)
    print(#G_human033.degree[hubs==1].sum() / G_human033.degree.sum() / hubs.sum(), 
          G_human033.nodal_cost[hubs==1].sum() / G_human033.nodal_cost.sum() / hubs.sum(), 
          #G_human033.nodal_cost[hubs==1].sum() / G_human033.nodal_cost.sum() / hubs.sum() / (G_human033.degree[hubs==1].sum() / G_human033.degree.sum() / hubs.sum()),
          G_human033.in_flow[hubs==1].sum() / G_human033.total_flow / hubs.sum(), 
          G_human033.in_flow[hubs==1].sum() / G_human033.total_flow / hubs.sum() / (G_human033.nodal_cost[hubs==1].sum() / G_human033.nodal_cost.sum() / hubs.sum()), 
          G_human033.nodal_cost[hubs==0].sum() / G_human033.nodal_cost.sum() / np.where(hubs==0, 1, 0).sum(), 
          G_human033.in_flow[hubs==0].sum() / G_human033.total_flow / np.where(hubs==0, 1, 0).sum(),
          G_human033.in_flow[hubs==0].sum() / G_human033.total_flow / np.where(hubs==0, 1, 0).sum() / (G_human033.nodal_cost[hubs==0].sum() / G_human033.nodal_cost.sum() / np.where(hubs==0, 1, 0).sum()),
    )
    print(G_human033.nodal_time[hubs==1].sum() / G_human033.WEcostsLinear.sum() / hubs.sum())

0
0.012195121951219513 0.0358269061416196 2.937806303612807 nan nan nan
0.012195121951219514
1
0.012195121951219513 0.0358269061416196 2.937806303612807 nan nan nan
0.012195121951219514
2
0.012195121951219513 0.0358269061416196 2.937806303612807 nan nan nan
0.012195121951219514
3
0.012195121951219513 0.0358269061416196 2.937806303612807 nan nan nan
0.012195121951219514
4
0.012336979456993413 0.03611152629898212 2.9270962495209254 0.0007046639835335109 0.012772673395254482 18.12590638052252
0.012152965077058146
5
0.012709526559240871 0.03694287537772935 2.906707437569249 0.0021642320948030234 0.014065506037479476 6.499074693169469
0.01232871852152462
6
0.012709526559240871 0.03694287537772935 2.906707437569249 0.0021642320948030234 0.014065506037479476 6.499074693169469
0.01232871852152462
7
0.01282718495939742 0.03723325904538345 2.902683571121793 0.002461351625279737 0.014169071423656246 5.7566222063236925
0.012419728898150262
8
0.0130780197063381 0.037813861326589975 2.89140574610573

/Users/yingqiuzheng/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:9: RuntimeWarning: invalid value encountered in double_scalars
/Users/yingqiuzheng/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:10: RuntimeWarning: invalid value encountered in double_scalars
/Users/yingqiuzheng/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:11: RuntimeWarning: invalid value encountered in double_scalars


In [39]:
for k in range(1, G_human033.degree.max()):
    hubs = np.where(G_human033.degree>k, 1, 0)
    non_hubs = np.where(G_human033.degree>k, 0, 1)
    rich_club = np.outer(hubs, hubs) * G_human033.adj
    non_rich_club = (1 - rich_club) * G_human033.adj
    local = np.outer(non_hubs, non_hubs) * G_human033.adj
    
    print(k, 1/G_human033.adj.sum())
    print(G_human033.wiring_cost[rich_club==1].sum()/G_human033.wiring_cost.sum()/rich_club.sum(), 
          G_human033.WEflowsLinear_edge[rich_club==1].sum() / G_human033.total_flow / rich_club.sum() )
    print(G_human033.wiring_cost[non_rich_club==1].sum()/G_human033.wiring_cost.sum()/non_rich_club.sum(), 
          G_human033.WEflowsLinear_edge[non_rich_club==1].sum() / G_human033.total_flow / non_rich_club.sum())
    print(G_human033.wiring_cost[local==1].sum()/G_human033.wiring_cost.sum()/local.sum(), 
          G_human033.WEflowsLinear_edge[local==1].sum() / G_human033.total_flow / local.sum())
    

1 0.0007052186177715092
0.0007052186177715092 0.00207179570071425
nan nan
nan nan
2 0.0007052186177715092
0.0007052186177715092 0.00207179570071425
nan nan
nan nan
3 0.0007052186177715092
0.0007052186177715092 0.00207179570071425
nan nan
nan nan
4 0.0007052186177715092
0.0007082203347751298 0.0020652161835134956
0.0001761659958833778 0.003231435607347219
nan nan
5 0.0007052186177715092
0.0007120914081460694 0.002055735870947235
0.0004556278094322157 0.0026550210975163635
nan nan
6 0.0007052186177715092
0.0007120914081460694 0.002055735870947235
0.0004556278094322157 0.0026550210975163635
nan nan
7 0.0007052186177715092
0.0007140457421282595 0.0020552289150089233
0.00047333685101533414 0.00250699241751187
nan nan
8 0.0007052186177715092
0.0007209167585837444 0.0020611542719558675
0.0004559171910629167 0.002240791724091413
nan nan
9 0.0007052186177715092
0.0007165562751123175 0.0020475664071681033
0.0006291823723445667 0.0022342899846052575
0.0006462044676090056 0.002928525413516894
10 0

/Users/yingqiuzheng/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:11: RuntimeWarning: invalid value encountered in double_scalars
/Users/yingqiuzheng/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:12: RuntimeWarning: invalid value encountered in double_scalars
/Users/yingqiuzheng/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:13: RuntimeWarning: invalid value encountered in double_scalars
/Users/yingqiuzheng/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:14: RuntimeWarning: invalid value encountered in double_scalars
/Users/yingqiuzheng/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:9: RuntimeWarning: invalid value encountered in double_scalars
/Users/yingqiuzheng/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:10: RuntimeWarning: invalid value encountered in double_scalars
